#
#   |                                 |
#   ---+---+---+---+---+---+---+---+---
#      |   |   |   |   |   |   |   |
#      Y   G           W  BLU     BLK
#     Tx0 Rx0         P0  Tx1     GND  
#
# DS-123 2 Gang Switch
#
esphome:
  name: ds123-701f67
  platform: ESP8266
  board: esp01_1m

# Enable logging

# UART0 - TX:GPIO1, RX:GPIO3
# UART0_SWAP: TX: GPIO15, RX:GPIO13
# UART1 - TX: GPIO2, RX:None
    
logger:
  baud_rate: 115200
  hardware_uart: UART1

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome Fallback Hotspot"
    password: "00000000"

switch:
  - platform: gpio
    name: "DS-123 Relay 1"
    pin: GPIO4
    id: relay1
    on_turn_off:
      if:
        condition:
          - switch.is_on: led1
        then:
          - switch.turn_off: led1
    on_turn_on:
      if:
        condition:
          - switch.is_off: led1
        then:
          - switch.turn_on: led1
      
  - platform: gpio
    name: "DS-123 Relay 2"
    pin: GPIO13
    id: relay2
    on_turn_off:
      if:
        condition:
          - switch.is_on: led2
        then:
          - switch.turn_off: led2
    on_turn_on:
      if:
        condition:
          - switch.is_off: led2
        then:
          - switch.turn_on: led2
      
  # With this we can control the blue side of the LED.
  - platform: gpio
    id: led1
    pin:
      number: GPIO14
      inverted: True
  # With this we can control the blue side of the LED.
  - platform: gpio
    id: led2
    pin:
      number: GPIO1
      inverted: True      

binary_sensor:
  - platform: gpio
    id: button1
    name: "DS-123 Button 1"
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    on_press:
# Prevents unintended LED lit states.
      if:
        condition:
          - switch.is_off: relay1
        then:
          - switch.turn_on: led1
          - switch.turn_on: relay1
        else:
          - switch.turn_off: relay1
  - platform: gpio
    id: button2
    name: "DS-123 Button 2"
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    on_press:
# Prevents unintended LED lit states.
      if:
        condition:
          - switch.is_off: relay2
        then:
          - switch.turn_on: led2
          - switch.turn_on: relay2
        else:
          - switch.turn_off: relay2  
status_led:
  pin:
    number: GPIO0
    inverted: no
  
